# Autoformatter friendly markdownlint config
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: true
spaces: false
url: false
whitespace: false
ol-prefix: false
