services:
  local_postgres:
    image: postgres:14
    volumes:
      - pg-data-test:/var/lib/postgresql/data
      - .docker/db-init.sh:/docker-entrypoint-initdb.d/db_init.sh
    environment:
      - POSTGRES_PASSWORD=TEST-insecure-password
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim-lausanne-budgets_development_app_development
    ports:
      - 5432:5432

volumes:
  pg-data-test: {}
