services:
  local_postgres:
    image: postgres:12
    volumes:
      - pg-data-test:/var/lib/postgresql/data
      - .docker/db-init.sh:/docker-entrypoint-initdb.d/db_init.sh
    environment:
      - POSTGRES_PASSWORD=TEST-insecure-password
      - POSTGRES_USER=decidim
      - POSTGRES_MULTIPLE_DATABASES=decidim_dev,decidim_test
    ports:
      - 5432:5432

volumes:
  pg-data-test: {}
