# File written by Decidim generator
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/packs
  source_entry_path: entrypoints
  public_output_path: decidim-packs
  public_root_path: public
  webpack_compile_output: true
  cache_path: tmp/webpacker-cache
  extract_css: true
  additional_paths:
    - node_modules
    - app/packs
development:
  <<: *default
  compile: true
  cache: true
  dev_server:
    bonjour: true
    https: false
    port: 3035
    public: localhost:3035
    host: localhost
    hmr: false
    hot: "only"
    live_reload: true
    inline: true
    compress: true
    allowed_hosts: "all"
    use_local_ip: true
    disable_host_check: true
    client:
      logging: 'log'
      overlay:
        errors: true
        warnings: false
        runtimeErrors: false
      progress: true
    webSocketServer: 'sockjs'
    headers:
      'Access-Control-Allow-Origin': '*'
      'Content-Security-Policy': "script-src 'self' 'unsafe-eval'; connect-src 'self' ws://localhost:3035 http://localhost:3035"
      'X-Content-Security-Policy': "script-src 'self' 'unsafe-eval'; connect-src 'self' ws://localhost:3035 http://localhost:3035"
      'X-WebKit-CSP': "script-src 'self' 'unsafe-eval'; connect-src 'self' ws://localhost:3035 http://localhost:3035"
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
